<?php
$tracks = array(
  array('artiste' => '2pac','titre' => 'california love'),
  array('artiste' => '50 cent','titre' => 'in da club'),
  array('artiste' => 'adam lambert','titre' => 'whataya want from me'),
  array('artiste' => 'adele','titre' => 'rolling in the deep'),
  array('artiste' => 'adele','titre' => 'rumour has it'),
  array('artiste' => 'adele','titre' => 'set fire to the rain'),
  array('artiste' => 'adele','titre' => 'someone like you'),
  array('artiste' => 'afrojack &amp; eva simons','titre' => 'take over control'),
  array('artiste' => 'afrojack f/eva simons','titre' => 'take over control'),
  array('artiste' => 'akon','titre' => 'right now (na na na)'),
  array('artiste' => 'akon f/colby o\'donis &amp; kardinal offishall','titre' => 'beautiful'),
  array('artiste' => 'alex clare','titre' => 'too close'),
  array('artiste' => 'alexandra stan','titre' => 'mr. saxobeat'),
  array('artiste' => 'alicia keys','titre' => 'girl on fire'),
  array('artiste' => 'alicia keys','titre' => 'no one'),
  array('artiste' => 'all-american rejects','titre' => 'dirty little secret (guitars mixed down version)'),
  array('artiste' => 'all-american rejects','titre' => 'gives you hell'),
  array('artiste' => 'all-american rejects','titre' => 'move along'),
  array('artiste' => 'american authors','titre' => 'best day of my life'),
  array('artiste' => 'ariana grande','titre' => 'last christmas'),
  array('artiste' => 'ariana grande f/mac miller','titre' => 'the way'),
  array('artiste' => 'austin mahone','titre' => 'what about love'),
  array('artiste' => 'avicii','titre' => 'hey brother'),
  array('artiste' => 'avicii','titre' => 'wake me up'),
  array('artiste' => 'avril lavigne','titre' => 'here\'s to never growing up'),
  array('artiste' => 'avril lavigne','titre' => 'what the hell'),
  array('artiste' => 'baby bash','titre' => 'suga suga'),
  array('artiste' => 'bastille','titre' => 'pompeii'),
  array('artiste' => 'beyonce','titre' => 'crazy in love'),
  array('artiste' => 'beyonce','titre' => 'halo'),
  array('artiste' => 'beyonce','titre' => 'irreplaceable'),
  array('artiste' => 'beyonce','titre' => 'single ladies (put a ring on it)'),
  array('artiste' => 'beyonce','titre' => 'sweet dreams'),
  array('artiste' => 'black eyed peas','titre' => 'boom boom pow'),
  array('artiste' => 'black eyed peas','titre' => 'i gotta feeling'),
  array('artiste' => 'black eyed peas','titre' => 'imma be'),
  array('artiste' => 'black eyed peas','titre' => 'just can\'t get enough'),
  array('artiste' => 'black eyed peas','titre' => 'meet me halfway'),
  array('artiste' => 'black eyed peas','titre' => 'where is the love'),
  array('artiste' => 'blink 182','titre' => 'all the small things'),
  array('artiste' => 'bonnie mckee','titre' => 'american girl'),
  array('artiste' => 'breathe carolina','titre' => 'blackout'),
  array('artiste' => 'britney spears','titre' => '3'),
  array('artiste' => 'britney spears','titre' => 'hold it against me'),
  array('artiste' => 'britney spears','titre' => 'i wanna go'),
  array('artiste' => 'britney spears','titre' => 'ooh la la'),
  array('artiste' => 'britney spears','titre' => 'perfume'),
  array('artiste' => 'britney spears','titre' => 'till the world ends'),
  array('artiste' => 'britney spears','titre' => 'toxic'),
  array('artiste' => 'britney spears','titre' => 'womanizer'),
  array('artiste' => 'britney spears','titre' => 'work bitch'),
  array('artiste' => 'bruno mars','titre' => 'gorilla'),
  array('artiste' => 'bruno mars','titre' => 'grenade'),
  array('artiste' => 'bruno mars','titre' => 'it will rain'),
  array('artiste' => 'bruno mars','titre' => 'just the way you are'),
  array('artiste' => 'bruno mars','titre' => 'locked out of heaven'),
  array('artiste' => 'bruno mars','titre' => 'the lazy song'),
  array('artiste' => 'bruno mars','titre' => 'treasure'),
  array('artiste' => 'bruno mars','titre' => 'when i was your man'),
  array('artiste' => 'bruno mars','titre' => 'young girls'),
  array('artiste' => 'calvin harris','titre' => 'feel so close'),
  array('artiste' => 'calvin harris f/ayah marar','titre' => 'thinking about you'),
  array('artiste' => 'calvin harris f/ellie goulding','titre' => 'i need your love'),
  array('artiste' => 'calvin harris f/florence welch','titre' => 'sweet nothing'),
  array('artiste' => 'calvin harris f/ne-yo','titre' => 'let\'s go'),
  array('artiste' => 'capital cities','titre' => 'safe and sound'),
  array('artiste' => 'carly rae jepsen','titre' => 'call me maybe'),
  array('artiste' => 'cascada','titre' => 'evacuate the dancefloor'),
  array('artiste' => 'cascada','titre' => 'everytime we touch'),
  array('artiste' => 'cee lo green','titre' => 'forget you'),
  array('artiste' => 'cher lloyd f/snoop dogg','titre' => 'want u back'),
  array('artiste' => 'chris brown','titre' => 'don\'t wake me up'),
  array('artiste' => 'chris brown','titre' => 'fine china'),
  array('artiste' => 'chris brown','titre' => 'forever'),
  array('artiste' => 'chris brown','titre' => 'run it! (remix)'),
  array('artiste' => 'chris brown','titre' => 'she ain\'t you'),
  array('artiste' => 'chris brown','titre' => 'turn up the music'),
  array('artiste' => 'chris brown','titre' => 'with you (main version)'),
  array('artiste' => 'chris brown','titre' => 'yeah 3x'),
  array('artiste' => 'chris wallace','titre' => 'remember when (push rewind)'),
  array('artiste' => 'christina aguilera','titre' => 'the christmas song'),
  array('artiste' => 'cobra starship f/leighton meester','titre' => 'good girls go bad'),
  array('artiste' => 'cobra starship f/sabi','titre' => 'you make me feel'),
  array('artiste' => 'cody simpson','titre' => 'pretty brown eyes'),
  array('artiste' => 'colby o f/akon','titre' => 'what you got'),
  array('artiste' => 'coldplay','titre' => 'viva la vida'),
  array('artiste' => 'conor maynard f/ne-yo','titre' => 'turn around'),
  array('artiste' => 'daft punk f/pharrell','titre' => 'get lucky'),
  array('artiste' => 'daughtry','titre' => 'no surprise'),
  array('artiste' => 'david guetta f/akon','titre' => 'sexy chick'),
  array('artiste' => 'david guetta f/flo rida &amp; nicki minaj','titre' => 'where them girls at'),
  array('artiste' => 'david guetta f/kid cudi','titre' => 'memories'),
  array('artiste' => 'david guetta f/nicki minaj','titre' => 'turn me on'),
  array('artiste' => 'david guetta f/rihanna','titre' => 'who\'s that chick'),
  array('artiste' => 'david guetta f/sia','titre' => 'titanium'),
  array('artiste' => 'david guetta f/usher','titre' => 'without you'),
  array('artiste' => 'demi lavato','titre' => 'give your heart a break'),
  array('artiste' => 'demi lavato','titre' => 'heart attack'),
  array('artiste' => 'demi lovato','titre' => 'neon lights'),
  array('artiste' => 'destiny\'s child','titre' => 'say my name'),
  array('artiste' => 'dev','titre' => 'in the dark'),
  array('artiste' => 'dj sammy','titre' => 'heaven'),
  array('artiste' => 'drake','titre' => 'best i ever had'),
  array('artiste' => 'drake','titre' => 'find your love'),
  array('artiste' => 'drake f/majid jordan','titre' => 'hold on we\'re going home'),
  array('artiste' => 'drake f/rihanna','titre' => 'take care'),
  array('artiste' => 'ed sheeran','titre' => 'the a team'),
  array('artiste' => 'edward maya f/vika jigulina','titre' => 'stereo love'),
  array('artiste' => 'ellie goulding','titre' => 'anything could happen'),
  array('artiste' => 'ellie goulding','titre' => 'burn'),
  array('artiste' => 'ellie goulding','titre' => 'lights'),
  array('artiste' => 'emblem3','titre' => 'chloe (you\'re the one i want)'),
  array('artiste' => 'emeli sande','titre' => 'next to me'),
  array('artiste' => 'eminem','titre' => 'bezerk'),
  array('artiste' => 'eminem','titre' => 'lose yourself'),
  array('artiste' => 'eminem f/rihanna','titre' => 'love the way you lie'),
  array('artiste' => 'eminem f/rihanna','titre' => 'the monster'),
  array('artiste' => 'enrique iglesias','titre' => 'heart attack'),
  array('artiste' => 'enrique iglesias','titre' => 'turn the night up'),
  array('artiste' => 'enrique iglesias f/ludacris','titre' => 'tonight'),
  array('artiste' => 'enrique iglesias f/pitbull','titre' => 'i like it'),
  array('artiste' => 'estelle f/kanye west','titre' => 'american boy'),
  array('artiste' => 'fall out boy','titre' => 'alone together'),
  array('artiste' => 'fall out boy','titre' => 'my songs know what you did in the dark (light em up)'),
  array('artiste' => 'fall out boy','titre' => 'sugar, we\'re goin\' down (guitars down version)'),
  array('artiste' => 'fall out boy','titre' => 'thnks fr the mmrs'),
  array('artiste' => 'far east movement f/ryan tedder','titre' => 'rocketeer'),
  array('artiste' => 'far east movement feat. cataracs &amp; dev','titre' => 'like a g6'),
  array('artiste' => 'fat joe','titre' => 'what\'s luv? (extra clean)'),
  array('artiste' => 'fergie','titre' => 'big girls don\'t cry'),
  array('artiste' => 'fergie','titre' => 'clumsy'),
  array('artiste' => 'fergie f/ludacris','titre' => 'glamorous'),
  array('artiste' => 'fifth harmony','titre' => 'miss movin\' on'),
  array('artiste' => 'flo rida','titre' => 'good feeling'),
  array('artiste' => 'flo rida','titre' => 'how i feel'),
  array('artiste' => 'flo rida','titre' => 'i cry'),
  array('artiste' => 'flo rida','titre' => 'right round'),
  array('artiste' => 'flo rida','titre' => 'whistle'),
  array('artiste' => 'flo rida f/david guetta','titre' => 'club can\'t handle me'),
  array('artiste' => 'flo rida f/t-pain','titre' => 'low'),
  array('artiste' => 'flo-rida f/sia','titre' => 'wild ones'),
  array('artiste' => 'foster the people','titre' => 'pumped up kicks'),
  array('artiste' => 'fray','titre' => 'how to save a life'),
  array('artiste' => 'fray','titre' => 'over my head (cable car)'),
  array('artiste' => 'fray','titre' => 'you found me'),
  array('artiste' => 'fun','titre' => 'we are young'),
  array('artiste' => 'fun.','titre' => 'carry on'),
  array('artiste' => 'fun.','titre' => 'some nights'),
  array('artiste' => 'gavin degraw','titre' => 'i don\'t want to be'),
  array('artiste' => 'gavin degraw','titre' => 'not over you'),
  array('artiste' => 'gnarls barkley','titre' => 'crazy'),
  array('artiste' => 'gotye','titre' => 'somebody that i used to know'),
  array('artiste' => 'gwen stefani','titre' => 'hollaback girl'),
  array('artiste' => 'gwen stefani','titre' => 'the sweet escape'),
  array('artiste' => 'gym class heroes f/adam levine','titre' => 'stereo hearts'),
  array('artiste' => 'gym class heroes f/neon hitch','titre' => 'self back home (super clean)'),
  array('artiste' => 'gym class heros','titre' => 'cupids chokehold'),
  array('artiste' => 'hot chelle rae','titre' => 'tonight tonight'),
  array('artiste' => 'icona pop f/charli xcx','titre' => 'i love it (super clean)'),
  array('artiste' => 'imagine dragons','titre' => 'demons'),
  array('artiste' => 'imagine dragons','titre' => 'it\'s time'),
  array('artiste' => 'imagine dragons','titre' => 'radioactive'),
  array('artiste' => 'iyaz','titre' => 'replay'),
  array('artiste' => 'j-lo f/pittbull','titre' => 'on the floor'),
  array('artiste' => 'j. cole f/tlc','titre' => 'crooked smile'),
  array('artiste' => 'jamie foxx f/t-pain &amp; yung joc','titre' => 'blame it'),
  array('artiste' => 'jason derulo','titre' => 'in my head'),
  array('artiste' => 'jason derulo','titre' => 'marry me'),
  array('artiste' => 'jason derulo','titre' => 'ridin\' solo'),
  array('artiste' => 'jason derulo','titre' => 'the other side'),
  array('artiste' => 'jason derulo','titre' => 'whatcha say'),
  array('artiste' => 'jason mraz','titre' => 'i\'m yours (pop mix)'),
  array('artiste' => 'jay sean f/lil wayne','titre' => 'down'),
  array('artiste' => 'jay sean f/sean paul','titre' => 'do you remember'),
  array('artiste' => 'jay-z &amp; linkin park','titre' => 'numb/encore'),
  array('artiste' => 'jay-z f/alicia keys','titre' => 'empire state of mind'),
  array('artiste' => 'jay-z f/justin timberlake','titre' => 'holy grail'),
  array('artiste' => 'jay-z f/rihanna &amp; kanye west','titre' => 'run this town'),
  array('artiste' => 'jennifer lopez f./pitbull','titre' => 'live it up'),
  array('artiste' => 'jeremih f/50 cent','titre' => 'down on me'),
  array('artiste' => 'jessie j','titre' => 'domino'),
  array('artiste' => 'jessie j f/b.o.b.','titre' => 'price tag'),
  array('artiste' => 'john newman','titre' => 'love me again'),
  array('artiste' => 'jordin sparks','titre' => 'tattoo'),
  array('artiste' => 'jordin sparks f/chris brown','titre' => 'no air'),
  array('artiste' => 'justin bieber','titre' => 'as long as you love me'),
  array('artiste' => 'justin bieber','titre' => 'boyfriend'),
  array('artiste' => 'justin bieber','titre' => 'mistletoe'),
  array('artiste' => 'justin bieber f/ludacris','titre' => 'all around the world'),
  array('artiste' => 'justin bieber f/nicki minaj','titre' => 'beauty and a beat'),
  array('artiste' => 'justin timberlake','titre' => 'cry me a river'),
  array('artiste' => 'justin timberlake','titre' => 'like i love you'),
  array('artiste' => 'justin timberlake','titre' => 'mirrors'),
  array('artiste' => 'justin timberlake','titre' => 'my love'),
  array('artiste' => 'justin timberlake','titre' => 'rock your body'),
  array('artiste' => 'justin timberlake','titre' => 'sexyback'),
  array('artiste' => 'justin timberlake','titre' => 'suit &amp; tie'),
  array('artiste' => 'justin timberlake','titre' => 'summer love'),
  array('artiste' => 'justin timberlake','titre' => 'take back the night'),
  array('artiste' => 'justin timberlake','titre' => 'tko'),
  array('artiste' => 'justin timeberlake','titre' => 'what goes around...(comes around)'),
  array('artiste' => 'kanye west','titre' => 'gold digger'),
  array('artiste' => 'kanye west','titre' => 'heartless'),
  array('artiste' => 'kanye west featuring daft punk','titre' => 'stronger'),
  array('artiste' => 'kardinal offishall f/akon','titre' => 'dangerous'),
  array('artiste' => 'karmin','titre' => 'brokenhearted'),
  array('artiste' => 'karmin','titre' => 'sleigh ride'),
  array('artiste' => 'katy perry','titre' => 'california gurls'),
  array('artiste' => 'katy perry','titre' => 'e.t.'),
  array('artiste' => 'katy perry','titre' => 'firework'),
  array('artiste' => 'katy perry','titre' => 'hot n cold'),
  array('artiste' => 'katy perry','titre' => 'i kissed a girl'),
  array('artiste' => 'katy perry','titre' => 'last friday night (t.g.i.f.)'),
  array('artiste' => 'katy perry','titre' => 'part of me'),
  array('artiste' => 'katy perry','titre' => 'roar'),
  array('artiste' => 'katy perry','titre' => 'teenage dream'),
  array('artiste' => 'katy perry','titre' => 'the one that got away'),
  array('artiste' => 'katy perry','titre' => 'unconditionally'),
  array('artiste' => 'katy perry','titre' => 'waking up in vegas'),
  array('artiste' => 'katy perry','titre' => 'wide awake'),
  array('artiste' => 'katy perry f/juicy j','titre' => 'dark horse'),
  array('artiste' => 'ke$ha','titre' => 'blow'),
  array('artiste' => 'ke$ha','titre' => 'c\'mon'),
  array('artiste' => 'ke$ha','titre' => 'crazy kids'),
  array('artiste' => 'ke$ha','titre' => 'die young'),
  array('artiste' => 'ke$ha','titre' => 'take it off'),
  array('artiste' => 'ke$ha','titre' => 'we r who we r'),
  array('artiste' => 'ke$ha','titre' => 'your love is my drug'),
  array('artiste' => 'kelly clarkson','titre' => 'catch my breath'),
  array('artiste' => 'kelly clarkson','titre' => 'mr. know it all'),
  array('artiste' => 'kelly clarkson','titre' => 'my life would suck without you'),
  array('artiste' => 'kelly clarkson','titre' => 'people like us'),
  array('artiste' => 'kelly clarkson','titre' => 'since u been gone'),
  array('artiste' => 'kelly clarkson','titre' => 'stronger (what doesn\'t kill you)'),
  array('artiste' => 'kelly clarkson','titre' => 'underneath the tree'),
  array('artiste' => 'kelly rowland','titre' => 'wonderful christmastime'),
  array('artiste' => 'keri hilson f/kanye west &amp; ne-yo','titre' => 'knock you down'),
  array('artiste' => 'kesha','titre' => 'tik tok'),
  array('artiste' => 'kevin ross','titre' => 'favorite thing'),
  array('artiste' => 'kevin rudolf f/lil wayne','titre' => 'let it rock'),
  array('artiste' => 'kid cudi vs. crookers','titre' => 'day \'n\' nite'),
  array('artiste' => 'kings of leon','titre' => 'use somebody'),
  array('artiste' => 'krewella','titre' => 'alive'),
  array('artiste' => 'la roux','titre' => 'bulletproof'),
  array('artiste' => 'labrinth f/emeli sande','titre' => 'beneath your beautiful'),
  array('artiste' => 'lady gaga','titre' => 'alejandro'),
  array('artiste' => 'lady gaga','titre' => 'applause'),
  array('artiste' => 'lady gaga','titre' => 'bad romance'),
  array('artiste' => 'lady gaga','titre' => 'born this way'),
  array('artiste' => 'lady gaga','titre' => 'born this way'),
  array('artiste' => 'lady gaga','titre' => 'lovegame'),
  array('artiste' => 'lady gaga','titre' => 'paparazzi'),
  array('artiste' => 'lady gaga','titre' => 'poker face'),
  array('artiste' => 'lady gaga','titre' => 'the edge of glory'),
  array('artiste' => 'lady gaga f/beyonce','titre' => 'telephone'),
  array('artiste' => 'lady gaga f/colby o\'donis','titre' => 'just dance'),
  array('artiste' => 'lady gaga f/r kelly','titre' => 'do what u want'),
  array('artiste' => 'lana del rey','titre' => 'summertime sadness'),
  array('artiste' => 'leona lewis','titre' => 'better in time (single mix)'),
  array('artiste' => 'leona lewis','titre' => 'one more sleep'),
  array('artiste' => 'lil wayne','titre' => 'how to love'),
  array('artiste' => 'linkin park','titre' => 'in the end'),
  array('artiste' => 'lloyd','titre' => 'she\'s all i want for christmas'),
  array('artiste' => 'lmfao','titre' => 'sexy and i know it'),
  array('artiste' => 'lmfao f/lauren bennett','titre' => 'party rock anthem'),
  array('artiste' => 'lorde','titre' => 'royals'),
  array('artiste' => 'lorde','titre' => 'royals (the weekend remix)'),
  array('artiste' => 'lorde','titre' => 'team'),
  array('artiste' => 'ludacris f/usher &amp; david guetta','titre' => 'rest of my life'),
  array('artiste' => 'macklemore &amp; ryan lewis','titre' => 'same love'),
  array('artiste' => 'macklemore &amp; ryan lewis','titre' => 'thrift shop (xtra clean)'),
  array('artiste' => 'macklemore &amp; ryan lewis f/ray dalton','titre' => 'can\'t hold us (amended)'),
  array('artiste' => 'macklemore &amp; ryan lewis f/schoolboy q','titre' => 'white walls'),
  array('artiste' => 'mariah carey','titre' => 'all i want for christmas is you'),
  array('artiste' => 'mariah carey f./miguel','titre' => '#beautiful'),
  array('artiste' => 'mario','titre' => 'let me love you'),
  array('artiste' => 'maroon 5','titre' => 'daylight'),
  array('artiste' => 'maroon 5','titre' => 'love somebody'),
  array('artiste' => 'maroon 5','titre' => 'misery'),
  array('artiste' => 'maroon 5','titre' => 'one more night'),
  array('artiste' => 'maroon 5','titre' => 'this love'),
  array('artiste' => 'maroon 5 f/christina aguilera','titre' => 'moves like jagger'),
  array('artiste' => 'maroon 5 f/wiz khalifa','titre' => 'payphone'),
  array('artiste' => 'martin solveig &amp; dragonette','titre' => 'hello'),
  array('artiste' => 'martin solveig f/dragonette','titre' => 'hello'),
  array('artiste' => 'mike posner','titre' => 'cooler than me (single mix)'),
  array('artiste' => 'mike posner','titre' => 'please don\'t go'),
  array('artiste' => 'miley cyrus','titre' => 'party in the u.s.a.'),
  array('artiste' => 'miley cyrus','titre' => 'see you again'),
  array('artiste' => 'miley cyrus','titre' => 'we can\'t stop'),
  array('artiste' => 'miley cyrus','titre' => 'wrecking ball'),
  array('artiste' => 'n-sync','titre' => 'merry christmas, happy holidays'),
  array('artiste' => 'natasha bedingfield','titre' => 'pocketful of sunshine'),
  array('artiste' => 'natasha bedingfield','titre' => 'unwritten'),
  array('artiste' => 'ne-yo','titre' => 'beautiful monster'),
  array('artiste' => 'ne-yo','titre' => 'closer'),
  array('artiste' => 'ne-yo','titre' => 'let me love you'),
  array('artiste' => 'ne-yo','titre' => 'miss independent'),
  array('artiste' => 'neighbourhood','titre' => 'sweater weather'),
  array('artiste' => 'nelly','titre' => 'hot in herre'),
  array('artiste' => 'nelly','titre' => 'just a dream'),
  array('artiste' => 'nelly f/city spud','titre' => 'ride wit me (full length clean)'),
  array('artiste' => 'nelly furtado','titre' => 'promiscuious'),
  array('artiste' => 'nelly furtado','titre' => 'say it right'),
  array('artiste' => 'neon trees','titre' => 'animal'),
  array('artiste' => 'neon trees','titre' => 'everybody talks'),
  array('artiste' => 'nicki minaj','titre' => 'pound the alarm'),
  array('artiste' => 'nicki minaj','titre' => 'starships'),
  array('artiste' => 'nicki minaj','titre' => 'super bass'),
  array('artiste' => 'nicki minaj','titre' => 'va va voom'),
  array('artiste' => 'notorious b.i.g.','titre' => 'hypnotize'),
  array('artiste' => 'notorious b.i.g.','titre' => 'mo money mo problems'),
  array('artiste' => 'of monsters and men','titre' => 'little talks'),
  array('artiste' => 'olly murs','titre' => 'heart skips a beat'),
  array('artiste' => 'olly murs f/flo rida','titre' => 'troublemaker'),
  array('artiste' => 'one direction','titre' => 'best song ever'),
  array('artiste' => 'one direction','titre' => 'kiss you'),
  array('artiste' => 'one direction','titre' => 'little things'),
  array('artiste' => 'one direction','titre' => 'one thing'),
  array('artiste' => 'one direction','titre' => 'story of my life'),
  array('artiste' => 'one direction','titre' => 'what makes you beautiful'),
  array('artiste' => 'onerepublic','titre' => 'all the right moves (rhythmix remix)'),
  array('artiste' => 'onerepublic','titre' => 'christmas without you'),
  array('artiste' => 'onerepublic','titre' => 'counting stars'),
  array('artiste' => 'onerepublic','titre' => 'good life (pop mix)'),
  array('artiste' => 'onerepublic','titre' => 'secrets'),
  array('artiste' => 'onerepublic','titre' => 'stop and stare'),
  array('artiste' => 'outkast','titre' => 'hey ya!'),
  array('artiste' => 'owl city','titre' => 'fireflies'),
  array('artiste' => 'owl city &amp; carly rae jepsen','titre' => 'good time'),
  array('artiste' => 'p!nk','titre' => 'f**kin\' perfect'),
  array('artiste' => 'panic! at the disco','titre' => 'i write sins not tragedies'),
  array('artiste' => 'paramore','titre' => 'still into you'),
  array('artiste' => 'passenger','titre' => 'let her go'),
  array('artiste' => 'phillip phillips','titre' => 'home'),
  array('artiste' => 'pink','titre' => 'blow me (one last kiss)'),
  array('artiste' => 'pink','titre' => 'please don\'t leave me'),
  array('artiste' => 'pink','titre' => 'raise your glasses'),
  array('artiste' => 'pink','titre' => 'so what'),
  array('artiste' => 'pink','titre' => 'sober'),
  array('artiste' => 'pink','titre' => 'try'),
  array('artiste' => 'pink','titre' => 'u + ur hand'),
  array('artiste' => 'pink','titre' => 'who knew'),
  array('artiste' => 'pink f/lily allen','titre' => 'true love'),
  array('artiste' => 'pink f/nate ruess','titre' => 'just give me a reason'),
  array('artiste' => 'pitbull','titre' => 'i know you want me (calle ocho) (clean english edit)'),
  array('artiste' => 'pitbull f/chris brown','titre' => 'international love'),
  array('artiste' => 'pitbull f/christina aguilera','titre' => 'feel this moment'),
  array('artiste' => 'pitbull f/danny mercer','titre' => 'outta nowhere'),
  array('artiste' => 'pitbull f/ke$ha','titre' => 'timber'),
  array('artiste' => 'pitbull f/ne-yo, afrojack &amp; nayer','titre' => 'give me everything'),
  array('artiste' => 'pitbull f/t-pain','titre' => 'hey baby (drop it to the floor)'),
  array('artiste' => 'pitbull f/tjr','titre' => 'don\'t stop the party'),
  array('artiste' => 'puff daddy','titre' => 'i\'ll be missing you'),
  array('artiste' => 'r kelly','titre' => 'ignition (remix)'),
  array('artiste' => 'rihanna','titre' => 'diamonds'),
  array('artiste' => 'rihanna','titre' => 'disturbia'),
  array('artiste' => 'rihanna','titre' => 'don\'t stop the music'),
  array('artiste' => 'rihanna','titre' => 'only girl (in the world)'),
  array('artiste' => 'rihanna','titre' => 'rude boy'),
  array('artiste' => 'rihanna','titre' => 's&amp;m'),
  array('artiste' => 'rihanna','titre' => 's.o.s. (rescue me)'),
  array('artiste' => 'rihanna','titre' => 'take a bow'),
  array('artiste' => 'rihanna','titre' => 'what now'),
  array('artiste' => 'rihanna','titre' => 'where have you been'),
  array('artiste' => 'rihanna f/calvin harris','titre' => 'we found love'),
  array('artiste' => 'rihanna f/david guetta','titre' => 'right now'),
  array('artiste' => 'rihanna f/drake','titre' => 'what\'s my name (revised clean)'),
  array('artiste' => 'rihanna f/jay-z','titre' => 'umbrella'),
  array('artiste' => 'rihanna f/mikky ekko','titre' => 'stay'),
  array('artiste' => 'rita ora','titre' => 'how we do (party)'),
  array('artiste' => 'robin thicke f/kendrick lamar','titre' => 'give it 2 u'),
  array('artiste' => 'robin thicke f/pharrell &amp; t.i.','titre' => 'blurred lines'),
  array('artiste' => 'ron reeser &amp; dan saenz f/myah','titre' => 'everything'),
  array('artiste' => 'sara bareilles','titre' => 'love song'),
  array('artiste' => 'sean kingston','titre' => 'fire burning'),
  array('artiste' => 'sean paul','titre' => 'temperature'),
  array('artiste' => 'selena gomez','titre' => 'come &amp; get it'),
  array('artiste' => 'selena gomez','titre' => 'slow down'),
  array('artiste' => 'selena gomez','titre' => 'who says'),
  array('artiste' => 'selena gomez &amp; the scene','titre' => 'love you like a love song'),
  array('artiste' => 'selena gomez &amp; the scene','titre' => 'naturally'),
  array('artiste' => 'shinedown','titre' => 'second chance'),
  array('artiste' => 'sonique','titre' => 'it feels so good'),
  array('artiste' => 'swedish house mafia','titre' => 'don\'t you worry child'),
  array('artiste' => 'swedish house mafia','titre' => 'save the world'),
  array('artiste' => 'taio cruz','titre' => 'dynamite'),
  array('artiste' => 'taio cruz f/ludacris','titre' => 'break your heart'),
  array('artiste' => 'taylor swift','titre' => '22'),
  array('artiste' => 'taylor swift','titre' => 'i knew you were trouble'),
  array('artiste' => 'taylor swift','titre' => 'we are never ever getting back together (pop mix)'),
  array('artiste' => 'tegan &amp; sara','titre' => 'closer'),
  array('artiste' => 'the killers','titre' => 'mr. brightside'),
  array('artiste' => 'the killers','titre' => 'somebody told me'),
  array('artiste' => 'the lumineers','titre' => 'ho hey'),
  array('artiste' => 'the script','titre' => 'breakeven'),
  array('artiste' => 'the script','titre' => 'for the first time'),
  array('artiste' => 'the script','titre' => 'hall of fame'),
  array('artiste' => 'the summer set','titre' => 'this christmas'),
  array('artiste' => 'the wanted','titre' => 'chasing the sun'),
  array('artiste' => 'the wanted','titre' => 'glad you came'),
  array('artiste' => 'ti','titre' => 'whatever you like'),
  array('artiste' => 'ti f/justin timberlake','titre' => 'dead and gone'),
  array('artiste' => 'ti f/rihanna','titre' => 'live your life'),
  array('artiste' => 'timbaland f/justin timberlake','titre' => 'carry out'),
  array('artiste' => 'timbaland f/keri hilson','titre' => 'the way i are'),
  array('artiste' => 'timbaland f/onerepublic','titre' => 'apologize'),
  array('artiste' => 'train','titre' => '50 ways to say goodbye'),
  array('artiste' => 'train','titre' => 'drive by (guitar up mix)'),
  array('artiste' => 'train','titre' => 'hey, soul sister'),
  array('artiste' => 'travie mccoy f/jason mraz','titre' => 'rough water'),
  array('artiste' => 'travis mccoy f/bruno mars','titre' => 'billionaire'),
  array('artiste' => 'trey songz f/fabolous','titre' => 'say aah'),
  array('artiste' => 'trey songz f/nicki minaj','titre' => 'bottoms up'),
  array('artiste' => 'usher','titre' => 'more (red one remix)'),
  array('artiste' => 'usher','titre' => 'scream'),
  array('artiste' => 'usher','titre' => 'u got it bad'),
  array('artiste' => 'usher','titre' => 'yeah!'),
  array('artiste' => 'usher f/pitbull','titre' => 'dj got us fallin\' in love'),
  array('artiste' => 'usher f/will.i.am','titre' => 'omg'),
  array('artiste' => 'usher f/young jeezy','titre' => 'love in this club'),
  array('artiste' => 'will.i.am f/britney spears','titre' => 'scream &amp; shout'),
  array('artiste' => 'will.i.am f/justin bieber','titre' => '#thatpower'),
  array('artiste' => 'wiz khalifa &amp; snoop dogg f/bruno mars','titre' => 'young, wild &amp; free'),
  array('artiste' => 'young money f/lloyd','titre' => 'bedrock'),
  array('artiste' => 'zedd f/foxes','titre' => 'clarity'),
  array('artiste' => 'zedd f/hayley williams','titre' => 'stay the night')
);
foreach($tracks as $item) {
    exec('touch "music/'.$item['artiste']." - ".$item['titre'].'.mp3"');
}